### ISSUE TITLE
Numactl feature not used everywhere it should be

### ISSUE THREAD

**Issue by henrifroese** [bitnami/bitnami-docker-mongodb-sharded#22] opened 2021-09-14 06:52 UTC
PR #17 added the numactl feature and uses it in `4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh`.

However, as far as I can tell after setup, mongod is actually launched in `run.sh` (from line 31) (e.g. https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-sharded/run.sh) so we'd need the same change as applied to `libmongodb.sh` there as well.

**Comment by juan131** [comment] 2021-09-14 06:55
Closing as duplicate of https://github.com/bitnami/charts/issues/7479

**Closed by juan131** 2021-09-14 06:55 UTC

**Comment by henrifroese** [comment] 2021-09-14 07:00
Is it a duplicate? Because this is about changes to the `run.sh` and not the `true/yes` issue

**Comment by juan131** [comment] 2021-09-14 13:11
Solved at https://github.com/bitnami/bitnami-docker-mongodb-sharded/commit/1a2f3018fe9e7fbd67e6966df1b1cb73ede4afb5 and https://github.com/bitnami/bitnami-docker-mongodb-sharded/commit/0e76a9a0307472c9d136af0c2f5ce279ce301ac1
